- name: Deploy Python Apps with Docker
  hosts: all
  become: true
  tasks:
    - name: Install Docker and dependencies
      ansible.builtin.apt:
        name: [docker.io, docker-compose]
        state: present
      when: ansible_os_family == "Debian"

    - name: Copy project files to the server
      ansible.builtin.copy:
        src: .
        dest: /home/{{ ansible_user }}/app
        mode: preserve

    - name: Build Docker images
      ansible.builtin.shell:
        cmd: docker-compose -f /home/{{ ansible_user }}/app/docker-compose.yml build
      args:
        chdir: /home/{{ ansible_user }}/app

    - name: Start containers
      ansible.builtin.shell:
        cmd: docker-compose -f /home/{{ ansible_user }}/app/docker-compose.yml up -d
      args:
        chdir: /home/{{ ansible_user }}/app

    - name: Configure application
      ansible.builtin.command:
        cmd: docker exec backend python manage.py migrate
      ignore_errors: true
