- name: Deploy Application
  hosts: myserver
  become: true
  vars:
    app_dir: /opt/myapp
    docker_compose_file: docker-compose.yml

  tasks:
    - name: Install required packages
      apt:
        name:
          - docker.io
          - docker-compose
        state: present
        update_cache: yes

    - name: Create application directory
      file:
        path: "{{ app_dir }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'

    - name: Copy application files to remote
      copy:
        src: "{{ item }}"
        dest: "{{ app_dir }}/{{ item }}"
      with_items:
        - Dockerfile
        - docker-compose.yml
        - .env
        - frontend/
        - backend/

    - name: Build Docker images
      command:
        cmd: docker-compose -f "{{ app_dir }}/{{ docker_compose_file }}" build
      args:
        chdir: "{{ app_dir }}"

    - name: Start application containers
      command:
        cmd: docker-compose -f "{{ app_dir }}/{{ docker_compose_file }}" up -d
      args:
        chdir: "{{ app_dir }}"

    - name: Ensure application is running
      command:
        cmd: docker ps
      register: docker_status

    - name: Display running containers
      debug:
        var: docker_status.stdout_lines